project_id = "jtkrgxrutwbcjgruexuf"

[functions.realtime-voice]
verify_jwt = false

[functions.ai-search]
verify_jwt = false

[functions.uta-data-ingestion]
verify_jwt = false

[functions.unified-search]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false
