-- Create scholarships table to store UTA scholarship information
CREATE TABLE public.scholarships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'merit', 'need', 'specialized', etc.
  amount_min NUMERIC,
  amount_max NUMERIC,
  description TEXT,
  eligibility_requirements TEXT[],
  application_deadline DATE,
  renewable BOOLEAN DEFAULT false,
  contact_info TEXT,
  source_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.scholarships ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Public can read scholarships" 
ON public.scholarships 
FOR SELECT 
USING (true);

-- Insert UTA scholarship data
INSERT INTO public.scholarships (name, type, amount_min, amount_max, description, eligibility_requirements, application_deadline, renewable, contact_info, source_url) VALUES
('Presidential Scholarship', 'merit', 8000, 16000, 'UTA''s most prestigious scholarship for incoming freshmen with outstanding academic achievement', ARRAY['High school GPA of 3.5 or higher', 'SAT score of 1200+ or ACT score of 26+', 'Texas resident'], '2024-12-01'::date, true, 'Financial Aid Office: finaid@uta.edu, (817) 272-3561', 'https://www.uta.edu/student-affairs/financial-aid/scholarships'),

('Maverick Academic Scholarship', 'merit', 2000, 8000, 'Merit-based scholarship for incoming freshmen demonstrating academic excellence', ARRAY['High school GPA of 3.0 or higher', 'SAT score of 1000+ or ACT score of 21+'], '2024-12-01'::date, true, 'Financial Aid Office: finaid@uta.edu, (817) 272-3561', 'https://www.uta.edu/student-affairs/financial-aid/scholarships'),

('Allan Saxe Scholarship', 'merit', 1000, 2500, 'Scholarship for students demonstrating leadership and community service', ARRAY['Minimum 3.0 GPA', 'Demonstrated leadership experience', 'Community service involvement'], '2024-03-01'::date, false, 'Honors College: honors@uta.edu, (817) 272-7195', 'https://www.uta.edu/academics/schools-colleges/honors'),

('Transfer Excellence Scholarship', 'merit', 1000, 4000, 'For outstanding transfer students from community colleges', ARRAY['Transfer student status', 'Minimum 3.2 college GPA', 'Completed at least 24 credit hours'], '2024-03-01'::date, true, 'Financial Aid Office: finaid@uta.edu, (817) 272-3561', 'https://www.uta.edu/student-affairs/financial-aid/scholarships'),

('Engineering Excellence Scholarship', 'specialized', 2000, 6000, 'For high-achieving students in engineering programs', ARRAY['Enrolled in College of Engineering', 'Minimum 3.5 GPA', 'Full-time enrollment'], '2024-02-15'::date, true, 'College of Engineering: engineering@uta.edu, (817) 272-2671', 'https://www.uta.edu/academics/schools-colleges/engineering'),

('Nursing Excellence Scholarship', 'specialized', 1500, 4000, 'For students in the College of Nursing and Health Innovation', ARRAY['Enrolled in nursing program', 'Minimum 3.3 GPA', 'Texas resident'], '2024-02-01'::date, true, 'College of Nursing: nursing@uta.edu, (817) 272-2776', 'https://www.uta.edu/academics/schools-colleges/nursing'),

('Pell Grant Supplement', 'need', 500, 2000, 'Additional aid for students receiving federal Pell Grants', ARRAY['Federal Pell Grant recipient', 'Texas resident', 'Full-time enrollment'], NULL, false, 'Financial Aid Office: finaid@uta.edu, (817) 272-3561', 'https://www.uta.edu/student-affairs/financial-aid/grants'),

('Emergency Financial Assistance', 'need', 100, 1000, 'Short-term financial assistance for students facing unexpected emergencies', ARRAY['Enrolled UTA student', 'Demonstrated financial emergency', 'Good academic standing'], NULL, false, 'Dean of Students: dos@uta.edu, (817) 272-2648', 'https://www.uta.edu/student-affairs/dean-of-students'),

('International Student Merit Scholarship', 'merit', 3000, 10000, 'Merit-based scholarship for international students', ARRAY['International student status', 'Minimum 3.5 GPA', 'Full-time enrollment'], '2024-04-01'::date, true, 'International Education: international@uta.edu, (817) 272-2801', 'https://www.uta.edu/international'),

('Graduate Research Assistantship', 'specialized', 12000, 24000, 'Research assistantship with tuition waiver for graduate students', ARRAY['Graduate student status', 'Research experience', 'Faculty sponsor'], NULL, true, 'Graduate School: grad@uta.edu, (817) 272-2681', 'https://www.uta.edu/academics/schools-colleges/graduate-school');