// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtkrgxrutwbcjgruexuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0a3JneHJ1dHdiY2pncnVleHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDk0NzcsImV4cCI6MjA3MjU4NTQ3N30.d-a3EJ9GgaguJs58GwbO7szv28h8JtkrMAuO3f8qNRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});